name: gsutil
version: git
summary: A command line tool for interacting with cloud storage services. 
description: gsutil is a Python application that lets you access Google Cloud Storage from the command line. 
  
adopt-info: devmode # use 'strict' once you have the right plugs and slots

grade: stable
confinement: devmode

architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

apps:
  gsutil:
    command: bin/gsutil
    plugs:
      - home
      - network
      - removable-media

parts:
 gsutil:
    plugin: 
    source: https://github.com/GoogleCloudPlatform/gsutil.git
    source-type: git
    override-pull: |
      git clone https://github.com/GoogleCloudPlatform/gsutil.git src/github.com/GoogleCloudPlatform/gsutil
       cd src/github.com/GoogleCloudPlatform/gsutil
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/v//')"
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version "$(git describe --tags | sed 's/v//')"
      override-build: |
      export GOPATH=$PWD
      cd src/github.com/GoogleCloudPlatform/gsutil
      env CGO_ENABLED=0 GOOS=linux \
      go build --ldflags "-s -w \
        -X 'github.com/GoogleCloudPlatform/gsutil/version.GitCommit=$(git rev-list -1 HEAD)' \
        -X 'github.com/GoogleCloudPlatform/gsutil/version.Version=$(git describe --tags --abbrev=0)'" \
        -a -installsuffix cgo -o $SNAPCRAFT_PART_INSTALL/bin/gsutil
    build-snaps:
      - go
    build-packages:
      - git
      - sed
